image: aursu/rpmbuild:7.9.2009-docker

stages:
  - build
  - deploy
  - docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  RL8: 8.10.20240528
  RL8TAG: 8.10.20240528
  RL9: 9.4.20240523
  RL9TAG: 9.4.20240523
  CI_COMMIT_SHORT_SHA_RL8: ${CI_COMMIT_SHORT_SHA}-rocky-8
  CI_COMMIT_SHORT_SHA_GCC11: ${CI_COMMIT_SHORT_SHA}-gcc-11
  DNF0: rpmb.jfrog.io/artifactory/custom
  DNF2: rpmb.jfrog.io/artifactory/gcc11custom

rocky8build:
  stage: build
  variables:
    BUILD: rocky8build
  script:
    - docker volume create $CI_COMMIT_SHORT_SHA_RL8
    - docker-compose build --no-cache --pull --build-arg repopath=$DNF0 --build-arg gccrepopath=$DNF2 $BUILD
    - docker-compose run -v $CI_COMMIT_SHORT_SHA_RL8:/home/centos/rpmbuild/RPMS $BUILD

rocky8deploy:
  stage: deploy
  variables:
    FTPTRAY_USER: rocky-8
    FTPTRAY_REPO: gcc11custom
  script:
    - docker run --rm -v $CI_COMMIT_SHORT_SHA_RL8:/home/centos/rpmbuild/RPMS -e FTPTRAY_USER=$FTPTRAY_USER -e FTPTRAY_PASSWORD=$FTPTRAY_PASSWORD -e FTPTRAY_REPO=$FTPTRAY_REPO -e FTPTRAY_HOST=$FTPTRAY_HOST aursu/rpmbuild:ftptray /usr/local/bin/ftptray.py /home/centos/rpmbuild/RPMS

gcc11docker:
  stage: docker
  script:
    - docker-compose -f build/gcc-11/docker-compose.yml build --no-cache --pull --build-arg repopath=$DNF0 --build-arg gccrepopath=$DNF2
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker-compose -f build/gcc-11/docker-compose.yml push